Trie for 21.09.2017
alexander-bzikadze/DotNET_csc pull request #1
Opened 2017-09-10 11:04 UTC by alexander-bzikadze

To run - dotnet run

2017-10-02 04:19 UTC, VMAtm requested changes
На данный момент оценка 5/10

2017-10-02 04:19 UTC, VMAtm commented on Trie/Main.cs
> +namespace CL
Почему здесь CL? Что означает это название?

2017-10-02 04:19 UTC, VMAtm commented on Trie/Main.cs
> +            var t = new Trie.Trie();
Было бы здорово проверочный код оформить в виде Unit-тестов, и проверять не только оптимистичный сценарий.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Main.cs
> +﻿using System;
Кстати, если сразу на новой машине набрать `dotnet run` - приложение упадёт, так как нужно сначала восстановить зависимости командой `dotnet restore`.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +        /// Returns true if this set did not already contain the specified element
На будущее: Тройной комментарий обычно обозначает xml-документацию, чего здесь нет. Если нужен комментарий, используйте двойной: `//`

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +        public bool Add(string element)  {
Какой-то из методов `Add/Remove` работает с пустой строкой неверно. В условии не было сказано, как класс должен себя вести при попытке добавления/удаления пустой строки, но если её нельзя добавить (как в вашей реализации), то и удалить её должно быть нельзя.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +            var node = root;
Метод `Contains` работает неверно: минимальный пример, на основе вашего кода

            t.Add("12");
            t.Add("123");
            Console.WriteLine(t.Contains("1"));

Выводит `True`, хотя строку `1` в класс никто не добавлял. Перечитайте описание алгоритма по ссылке из условия - вы забыли про флаг `isTerminal`

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +using System;
`using System` в данном классе не требуется.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +        public Trie() {}
Пустой конструктор создаёт за вас компилятор, это ненужный код

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +                node.Size += 1;
Здесь и далее: В C#, в отличие, скажем, от Python, есть оператор инкремента, и в подобных случаях лучше пользоваться им (тоже касается и оператора декремента).

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +        private Node root = new Node();
Инициализацию этого поля как раз можно было бы вынести в конструктор (и тогда он не был бы пустым и ненужным). Так же поле можно отметить флагом `readonly`, так как инициализируется оно только в конструкторе. Так же имена private-переменные класса принято начинать с символа подчёркивания (как в Python, например), в данном случае `_root`.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +                this.Map = new Dictionary<char, Node>();
`this` здесь не требуется.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.cs
> +            public Dictionary<char, Node> Map { get; }
Имя поля `Map` абсолютно ничего не говорит тому, кто читает ваш код в первый раз (и в .Net принято слово `Dictionary`, а не `Map`, как в `Java`). Помогите другим, назовите поле более подходяще.

2017-10-02 04:19 UTC, VMAtm commented on Trie/Trie.csproj
> +    <OutputType>Exe</OutputType>
Тип приложения можно сделать не консольным, а той же библиотекой классов, а для проверки либо написать Unit-тесты, либо добавить приложение, вызывающее библиотеку.

2017-10-02 06:55 UTC, alexander-bzikadze commented on Trie/Trie.cs
> +        /// Returns true if this set did not already contain the specified element
Казалось бы, описательные комментарии к методам хочется увидеть в документации. Разве как раз в этом месте не хочется `///`? Другой вопрос, что комментарии в таком случае хочется более вразумительные.

2017-10-02 07:43 UTC, VMAtm commented on Trie/Trie.cs
> +        /// Returns true if this set did not already contain the specified element
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments

Речь идёт про то, что xml комментарии немного по-другому оформляются

2017-10-02 07:45 UTC, alexander-bzikadze commented on Trie/Trie.cs
> +        /// Returns true if this set did not already contain the specified element
Ага, тогда ясно. Спасибо

2017-10-13 02:30 UTC, VMAtm approved these changes
Оценка обновлена до 8/10

2017-10-13 02:30 UTC, VMAtm commented on Trie/Trie/Properties/AssemblyInfo.cs
> +using System.Runtime.CompilerServices;
`using` тут не нужен

2017-10-13 02:30 UTC, VMAtm commented on Trie/Trie/Tests/TrieTest.cs
> +            Assert.IsTrue(_trie.Add(""));
Здесь и далее: Unit-тесты обычно визуально разделяют на подготовку данных (в том числе ожидаемый результат), выполнений определённых действий и проверку результата, у вас получилось всё в двух строках. Тому, кто будет разбирать ваш код по тестам, будет немного сложно.

2017-10-13 02:30 UTC, VMAtm commented on Trie/Trie/Trie.cs
> +            if (!Contains(element)) {
Определитесь, где у вас  фигурные скобки - в конце строки или на новых строках

2017-10-16 19:42 UTC, merged