Mini-Roguelike added.
alexander-bzikadze/DotNET_csc pull request #4
Opened 2017-10-16 19:42 UTC by alexander-bzikadze

2017-11-13 04:15 UTC, VMAtm requested changes
На данный момент оценка 6/10

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/CharGameMapReader.cs
> +            _readStrings = File.ReadAllLines(_filename);
Стоило бы проверять, существует ли файл и успешно ли он прочитан

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/CharGameMapReader.cs
> +            return this;
Зачем этот return?

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +        private string _gameMapFileName = "./gameMap.txt";
Это поле не используется

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +        public event EventHandler<GameMapChangedArgs> MapChanged = (sender, args) => { };
Пустые обработчики событий, чтобы не вылетал `NullReference`? Лучше использовать `?.` в данном случае

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +            _gameMap = new CharGameMapReader(gameMapFileName).ReadFile().GetMap();
Метод `ReadFile` не должен возвращать объект, на который и так есть ссылка - вынесите метод на отдельную строку

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                            _player.MoveRight();
Вы двигаете фигурку игрока на старте?

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                    j++;
Несколько строк выше у вас постфиксный оператор

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                case ConsoleKey.Q:
Стоило подписаться на событие `Console.CancelKeyPress`: https://stackoverflow.com/a/29915430/213550

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                case ConsoleKey.RightArrow:
Не кажется ли вам, что эти случаи очень похожи? Меняются только константы и операции. Если уж и делать `switch`, то с помощью типизации, чтобы уже иметь объект с информацией. У вас же простой метод вылез за размеры экрана

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +            if (mapChanged)
Можно без флага, если обрабатывать ветку `default`

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/GameMap.cs
> +    internal class GameMap : IEnumerable<IEnumerable<bool>>
Очень сложное наследование. Ради красивого вызова вы наследуетесь от неочевидных базовых классов

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/GameMap.cs
> +                throw new NoNullAllowedException("Map has not been build yet!");
Использовать исключения в коде нужно для **исключительных** ситуаций, а не для проверок, инициализирован ли ваш класс

2017-11-13 04:15 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/gameMap.txt
> +###
Файл не добавлен в проект. Когда вы добавите, сделайте ему в свойствах `Copy to output directory: Always`, чтобы он всегда был в вашей исполняемой директории

2017-11-14 17:49 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/CharGameMapReader.cs
> +            return this;
Таков дизайн? В случае, если бы требовалось несколько раз подряд запускать void методы у некоего класса я, как и многие, предпочитаю вместо void его возвращать для последовательного запуска. Лишняя возвращаемая ссылка не должна сильно производительность влиять?

2017-11-14 17:51 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                case ConsoleKey.RightArrow:
Типизированный switch и 100500+ классов для этого? Уж лучше тогда что-то умнее)

2017-11-14 17:51 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                case ConsoleKey.RightArrow:
Если под типизацией имеется в виду отдельный класс под каждый случай, безусловно

2017-11-14 17:54 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +        public event EventHandler<GameMapChangedArgs> MapChanged = (sender, args) => { };
Достаточно давно Юрий данный способ рекомендовал. В чем принципиальное отличие и преимущество `?.` здесь? Чем лучше?

2017-11-14 17:55 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +            _gameMap = new CharGameMapReader(gameMapFileName).ReadFile().GetMap();
Не очень понятно, почему не должен. Логика - запуститься, изменить состояние, вернуть объект для дальнейшего исполнения. Зачем разбиение логики?

2017-11-23 22:47 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +        public event EventHandler<GameMapChangedArgs> MapChanged = (sender, args) => { };
`?.` - это решение для C# 6.0 и выше. До этого, для того чтобы убрать проверки на пустоту, действительно использовали пустые делегаты. Больше об этом вот здесь: https://codeblog.jonskeet.uk/2015/01/30/clean-event-handlers-invocation-with-c-6/

2017-11-23 22:54 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/CharGameMapReader.cs
> +            return this;
Дело здесь не в возвращаемой ссылке, а в том, что данная запись сложно читаема. Метод называется `ReadFile`, а возвращается `IGameMapReader`. Более того, вы оставляете пользователю вашего класса возможность вызвать `GetMap` без вызова `ReadFile`, что является раскрытием внутренней логики вашего класса, и является **плохим** дизайном в **данном** случае. Лично мне вообще непонятно, почему данный метод вообще является `public` - его вполне можно было бы сделать `private` и вызывать внутри вашего `GetMap`, тем самым сократив (и упростив) код.

2017-11-23 23:01 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +            _gameMap = new CharGameMapReader(gameMapFileName).ReadFile().GetMap();
Как уже написал, пользователь вашего класса не должен думать, вызвал он `ReadFile` или нет. Более того, он не должен думать, какую ссылку ему сохранять для дальнейшей работы - ту, что он получил при создании объекта, или ту, что вернул метод `ReadFile`. Именно вопрос `Зачем разбиение логики` здесь и висит - зачем вообще пользователю знать про метод `ReadFile`?

Подход с `return this` оправдан, когда есть разница между возвращаемыми значениями (когда вы пишете immutable класс, например), но в данном случае он просто запутывает того, кто видит ваш код.

Более того, если уж вы всё равно создаёте `IGameMapReader`, сделайте его переменной конструктора (убрав оттуда строку с именем файла вообще), следуя принципам inversion of control. В данном случае при изменении логики получения файла вам придётся менять и код класса `Map`, что опять-таки говорит о плохом дизайне.

2017-11-23 23:08 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                case ConsoleKey.RightArrow:
Не очень понял вашу иронию про большое количество классов. В вашем коде класс `Game` жёстко привязан к консоли. Если бы вы сделали два типа события (изменение позиции персонажа и выход из игры), ваш код был бы чище и меньше, и это было бы лучше, чем 4 практически одинаковых метода:

    switch (e.GameChange)
    {
        case PositionChange newP:
            // попробовать изменить местоположение игрока
        case CancelRequest cancel:
            // выход из игры
    }

2017-11-25 16:21 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/Game.cs
> +                            _player.MoveRight();
Это на случай, если стартовая позиция стена. Мы выполняем поиск позиции для игрока.

2017-11-25 17:03 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/GameMap.cs
> +                throw new NoNullAllowedException("Map has not been build yet!");
А что тогда в таком случае ожидается?
В другом языке я бы ассерт поставил бы

2017-11-25 17:04 UTC, alexander-bzikadze commented on Mini-Roguelike/Mini-Roguelike/GameMap.cs
> +    internal class GameMap : IEnumerable<IEnumerable<bool>>
На самом деле, не очень понятно, почему не очевидных. Вроде IEnumerable достаточно очевидный?

2017-12-01 04:16 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/GameMap.cs
> +    internal class GameMap : IEnumerable<IEnumerable<bool>>
Меня больше интересует `bool`. Представлять ячейки в виде `bool` - это решение для первой версии. А если появится третий тип ячейки? Вам придётся сильно переписывать код.

2017-12-01 04:17 UTC, VMAtm commented on Mini-Roguelike/Mini-Roguelike/GameMap.cs
> +                throw new NoNullAllowedException("Map has not been build yet!");
Так и ставьте `Assert`, если он для дебага - есть класс `Debug`. А ещё можно было бы сделать событие загрузки карты, и реагировать на него (так же оно могло бы запускаться после того, как персонаж поменял местоположение)

2017-12-02 14:41 UTC, alexander-bzikadze commented
Попытался в тестах копировать файлы-ресурсы, но не вышло. Чтобы работало нагуглил только такой вариант: https://stackoverflow.com/a/41955527

2017-12-03 12:04 UTC, merged